const R=window.DiffReview;
function esc(v){return String(v||"").replace(/[&<>]/g,(m)=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[m]))}
function filteredFiles(){return R.activeFiles().filter((f)=>!R.state.filter||f.path.toLowerCase().includes(R.state.filter.toLowerCase()))}
function renderItems(){const files=filteredFiles();R.ensureActiveFile();R.els.items.innerHTML=files.map((file)=>`<button class="${file.id===R.state.activeFileId?"active":""}" data-file="${file.id}">${esc(file.gitDiff?.displayPath||file.path)}</button>`).join("")||"<div class='meta'>No files</div>"}
function renderCommitSelect(){const on=R.state.scope==="commits";R.els.commitSelect.className=on?"":"hidden";R.els.commitSelect.innerHTML=R.data.commits.map((c)=>`<option value="${c.sha}" ${c.sha===R.state.selectedCommitSha?"selected":""}>${esc(c.shortSha)} ${esc(c.subject)}</option>`).join("");if(on&&R.state.selectedCommitSha&&!R.state.commitFiles[R.state.selectedCommitSha])R.requestCommit(R.state.selectedCommitSha)}
function renderDiff(){const file=R.findFile(R.state.activeFileId||"");const contents=R.activeContent();R.els.fileLabel.textContent=file?file.gitDiff?.displayPath||file.path:"Select a file";R.els.hint.textContent=R.state.scope==="commits"?"Commit review with line/file comments.":R.state.scope==="branch"?"Branch review against the detected base ref.":"Current-file review for changed files.";if(file&&!contents)R.requestFile(file.id);const rows=R.rows(contents||{originalContent:"",modifiedContent:""});const pane=(side,title,key)=>`<section class="pane"><h3>${title}</h3>${rows.map((row)=>`<div class="row ${row.cls}"><div class="num ${R.state.draft.side===side&&row[key]===R.state.draft.startLine?"pick":""}" data-side="${side}" data-line="${row[key]||""}">${row[key]||""}</div><pre class="code">${esc(side==="original"?row.left:row.right)}</pre></div>`).join("")}</section>`;R.els.diff.innerHTML=`<div class="diff">${pane("original",R.state.scope==="all"?"Current":"Original","leftNo")}${pane("modified","Modified","rightNo")}</div>`}
function renderDraft(){const target=R.state.draft.side==="file"?"File comment":`${R.state.draft.side} line ${R.state.draft.startLine}`;R.els.commentDraft.innerHTML=`<div class="comment draft"><div class="meta">${esc(target)}</div><textarea id="draft-body">${esc(R.state.draft.body)}</textarea><div><button data-action="file-comment">File comment</button><button data-action="save-comment">Save comment</button><button data-action="clear-draft">Clear</button></div></div>`}
function renderComments(){const scope=R.state.scope,sha=R.state.selectedCommitSha;const comments=R.state.comments.filter((c)=>c.scope===scope&&(scope!=="commits"||c.commitSha===sha));R.els.commentList.innerHTML=comments.map((comment)=>`<div class="comment"><strong>${esc(R.commentLabel(comment))}</strong><div>${esc(comment.body)}</div><button data-remove="${comment.id}">Remove</button></div>`).join("")||"<div class='meta'>No comments yet</div>"}
R.renderError=(message)=>{R.els.hint.textContent=message};
R.render=()=>{document.querySelectorAll("nav button").forEach((button)=>button.classList.toggle("active",button.dataset.scope===R.state.scope));R.els.meta.textContent=`${R.data.repoRoot}${R.data.branchBaseRef?` • base ${R.data.branchBaseRef}`:""}`;renderCommitSelect();renderItems();renderDiff();renderDraft();renderComments();};
