const DiffReview=window.DiffReview||{};window.DiffReview=DiffReview;
const reviewData=JSON.parse(document.getElementById("diff-review-data").textContent||"{}");
DiffReview.data={repoRoot:reviewData.repoRoot||"",files:Array.isArray(reviewData.files)?reviewData.files:[],commits:Array.isArray(reviewData.commits)?reviewData.commits:[],branchBaseRef:reviewData.branchBaseRef??null,branchMergeBaseSha:reviewData.branchMergeBaseSha??null,repositoryHasHead:reviewData.repositoryHasHead===true};
DiffReview.state={scope:DiffReview.data.files.some((f)=>f.inGitDiff)?"branch":DiffReview.data.commits.length?"commits":"all",activeFileId:null,selectedCommitSha:DiffReview.data.commits[0]?.sha||null,commitFiles:{},fileContents:{},comments:[],draft:{body:"",side:"file",startLine:null,endLine:null},overall:"",filter:"",seq:0};
DiffReview.els={meta:document.getElementById("meta"),items:document.getElementById("items"),commitSelect:document.getElementById("commit-select"),fileLabel:document.getElementById("file-label"),hint:document.getElementById("hint"),diff:document.getElementById("diff"),commentDraft:document.getElementById("comment-draft"),commentList:document.getElementById("comment-list"),overall:document.getElementById("overall"),refresh:document.getElementById("refresh")};
DiffReview.fileKey=(scope,sha,id)=>`${scope}\u0000${sha||""}\u0000${id}`;
DiffReview.activeFiles=()=>DiffReview.state.scope==="commits"?(DiffReview.state.commitFiles[DiffReview.state.selectedCommitSha||""]||[]):DiffReview.state.scope==="branch"?DiffReview.data.files.filter((f)=>f.inGitDiff):DiffReview.data.files;
DiffReview.findFile=(id)=>DiffReview.activeFiles().find((file)=>file.id===id)||DiffReview.data.files.find((file)=>file.id===id)||Object.values(DiffReview.state.commitFiles).flat().find((file)=>file.id===id)||null;
DiffReview.ensureActiveFile=()=>{const files=DiffReview.activeFiles().filter((f)=>!DiffReview.state.filter||f.path.toLowerCase().includes(DiffReview.state.filter.toLowerCase()));if(!files.length)return DiffReview.state.activeFileId=null;if(files.every((f)=>f.id!==DiffReview.state.activeFileId))DiffReview.state.activeFileId=files[0].id;};
